### ISSUE TITLE
Entrega S1

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#32]
Preparar y revisar los documentos de cara a la entrega del sprint 1.

- [x] Actas de reunión
- [x] Documento de análisis y requisitos del sistema DARS https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/12
- [x] Contribución individual detallada (clockify)
- [x] Estimación de costes https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/3
- [x] Ciclo de vida https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/22  
- [x] Usuarios piloto gestión https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/30
- [x] Informe y registro de riesgos   
- [x] Modelo de negocio y perfil de competidores   https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/6
- [ ] Gestión de evaluación de los miembros del equipo https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/26
- [x] pilots
- [x] Plan de gestión de la organización https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/2
- [x] Presentación https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/31
- [x] Registro de riesgos https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/29
- [x] Registro feedback usuarios piloto
- [x] report
- [x] Performance evaluation (puntación y tareas)
- [x] Contrato https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/25
- [x] niko niko https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/23  
- [x] Product backlog   
- [x] vídeo demo https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/34 
- [x] Retrospectiva https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/27
- [x] Gestión de la calidad del Software y documentación https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/28
- [x] Evaluacion del feedback del grupo 5
- [x] 6-revision

**Comment by Josdelsan** [comment]
Actualización menor en el **Plan de gestión de la Organización**. Se va a añadir el **contrato** como anexo a la hora de entregar.
Actualización del documento de **Gestión del Ciclo de Vida** acorde a los cambios realizados durante estas semanas.
