### ISSUE TITLE
Entrega S3

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/NGOs-documentation#52]

**Comment by lNoelia** [comment]
Preparar y revisar los documentos de cara a la entrega del sprint 2.

- [x] Actas de reunión
- [x] Contribución individual detallada (clockify)
- [x] Estimación de costes https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/63
- [x] Planes de inversion
- [x] Gestión de usuarios piloto
- [x] Informe y registro de riesgos https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/49  
- [x] Modelo de negocio y perfil de competidores   https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/6
- [x] Gestión de evaluación de los miembros del equipo https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/26
- [x] pilots
- [x] Presentación https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/55
- [x] Registro feedback usuarios piloto https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/44
- [x] report
- [x] Performance evaluation (puntación y tareas)
- [x] vídeo demo https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/45
- [x] Anuncio Manuel Quinto https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/45
- [x] Anuncio Mayores https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/45
- [x] Retrospectiva https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/48
- [x] Gestión de la calidad del Software y documentación https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/28
- [x] Evaluacion del feedback del grupo 5
- [x] 6-revision
- [x] Documento de impacto legal del proyecto
- [x] Documento de los SLAs
